// src/routes/details/movie/[id].tsx
//
// Backwards-compatibility redirect: old share links used the
// `/details/movie/{id}` URL pattern (generated by a bug in the share
// handler). The canonical deep-link route is `/movie/{id}` (see
// src/routes/movie/[id].tsx). This redirect catches old share links
// still in circulation and forwards them to the correct route so
// users don't see a blank page.
//
// New share links are generated with the correct `/movie/{id}` path
// directly (see UpcomingPage.tsx handleShare), so this redirect is
// only needed for legacy links.
import { Navigate, useParams } from "@solidjs/router";

export default function DetailsMovieRedirect() {
  const params = useParams();
  return <Navigate href={`/movie/${params.id}`} />;
}
