// src/routes/details/tv/[id].tsx
//
// Backwards-compatibility redirect: old share links used the
// `/details/tv/{id}` URL pattern (generated by a bug in the share
// handler). The canonical deep-link route is `/tv/{id}` (see
// src/routes/tv/[id].tsx). This redirect catches old share links
// still in circulation (WhatsApp messages, Telegram forwards, etc.)
// and forwards them to the correct route so users don't see a blank
// page.
//
// New share links are generated with the correct `/tv/{id}` path
// directly (see UpcomingPage.tsx handleShare), so this redirect is
// only needed for legacy links.
import { Navigate, useParams } from "@solidjs/router";

export default function DetailsTvRedirect() {
  const params = useParams();
  return <Navigate href={`/tv/${params.id}`} />;
}
