// src/features/discover/components/AiRecommendationRail.tsx
//
// CineLog V2 — AI Picks for You rail (Phase 16 Chunk 2)
// ---------------------------------------------------------------------
// A Discover section that shows 3 "hidden gem" movie recommendations
// generated by Groq based on the user's top 5 highest-rated vault
// items. Renders as the ABSOLUTE LAST section on the Discover page
// (below "Coming Soon").
//
// LIFECYCLE:
//   1. On mount, fetch /api/ai/status (public, CDN-cached). If
//      masterEnabled=false OR userRecommendationsEnabled=false, render
//      nothing — the rail is invisible. This is the client-side gate
//      that mirrors the server-side isAiFeatureEnabled() check.
//   2. If enabled, fetch /api/discover/ai-recommendations. The route:
//        - Checks the 24h cache in user_preferences.prefs_json.aiRecs.
//        - On cache hit: returns the cached 3 movies immediately.
//        - On cache miss: fetches top 5 vault items, calls Groq,
//          fetches TMDB metadata, caches the result, returns 3 movies.
//   3. Render the 3 movies in a DiscoverRail (same component used by
//      every other Discover section — visual consistency).
//
// ERROR / EDGE CASE HANDLING (Rule 3 — fail gracefully):
//   - Guest user → don't render (no vault → no recommendations).
//   - Feature disabled (/api/ai/status returns false) → don't render.
//   - 202 with empty movies + reason → show the reason in a friendly
//     empty state ("Rate at least 3 movies to unlock AI recs").
//   - 403 (feature disabled server-side, e.g. admin toggled it off
//     between the status check + the recs fetch) → don't render.
//   - 503 (Groq failure / rate limit) → show a retry button.
//   - Network error → show a retry button.
//   In ALL error cases, the rail never crashes the Discover page —
//   it just shows an empty state or hides itself.
//
// REFETCH STRATEGY:
//   The component fetches once on mount. There's no auto-refresh —
//   the 24h cache means re-fetching within the same day would just
//   return the same 3 movies. The user can click "Refresh" to force
//   a re-fetch (which will hit the server cache unless 24h have
//   passed). The Refresh button is shown in the section header.
//
// PLACEMENT:
//   This component is rendered by DiscoverPage as the LAST section,
//   after "Coming Soon" (section 8). See DiscoverPage.tsx.

import {
  createResource,
  createMemo,
  Show,
  For,
  type Component
} from "solid-js";
import DiscoverEmptyState from "~/features/discover/components/DiscoverEmptyState";
import { DisabledState, RateLimitState } from "~/shared/ui/states";
import { getAuthHeaders } from "~/lib/supabase/session";
import { tmdbImage } from "~/core/tmdb/tmdb";
import type { TMDBTitle } from "~/shared/types";

// ─── Types ───────────────────────────────────────────────────────

/** Public AI status response from /api/ai/status. */
interface AiStatus {
  masterEnabled: boolean;
  userRecommendationsEnabled: boolean;
}

/** Response from /api/discover/ai-recommendations. */
interface AiRecsResponse {
  movies: TMDBTitle[];
  reason?: string;
  source: "cache" | "fresh";
  generatedAt: string;
}

interface AiRecommendationRailProps {
  /** Called when the user clicks a movie card. Opens the Details modal. */
  onSelect: (title: TMDBTitle) => void;
  /** True when the user is a guest (no vault → no recommendations). */
  isGuest: boolean;
}

// ─── Fetchers ────────────────────────────────────────────────────

/** Fetch the public AI status. Returns null on any error (rail hides).
 *  This endpoint is public (no auth required) — we still send credentials
 *  so that an existing session cookie (if any) is forwarded, but the
 *  route works fine without it. */
async function fetchAiStatus(): Promise<AiStatus | null> {
  try {
    const resp = await fetch("/api/ai/status", { credentials: "include" });
    if (!resp.ok) return null;
    const data = (await resp.json()) as AiStatus;
    return data;
  } catch {
    return null;
  }
}

/**
 * Fetch the AI recommendations. Returns either the movies array or
 * an error/reason object. The caller distinguishes via the discriminated
 * union.
 */
type RecsResult =
  | { ok: true; data: AiRecsResponse }
  | { ok: false; reason: "rate_limit" | "unavailable" | "needs_more_ratings" | "network"; message?: string };

async function fetchAiRecs(): Promise<RecsResult> {
  // Phase 18 deep-fix v2: read the auth headers FIRST. If no session
  // is active (no access token in localStorage), DON'T fire the
  // request — the route would 401 and the browser would log a red
  // "Failed to load resource: 401" error to the console. The rail
  // hides itself in this case (the parent Show gates on !isGuest,
  // but a session can expire between mount + fetch). Returning
  // "unavailable" is correct: the rail stays hidden, no console
  // error, no UI flicker. The next render with a valid session will
  // fire the fetch properly.
  const authHeaders = await getAuthHeaders();
  if (!authHeaders.Authorization) {
    return { ok: false, reason: "unavailable", message: "Sign in to get AI recommendations." };
  }

  let resp: Response;
  try {
    resp = await fetch("/api/discover/ai-recommendations", {
      credentials: "include",
      headers: {
        Accept: "application/json",
        ...authHeaders
      }
    });
  } catch {
    return { ok: false, reason: "network" };
  }

  // 401 = no valid session (signed-out, expired token, or the auth
  // header was missing). The rail should hide entirely — a guest
  // wouldn't have reached this fetch because the outer Show gates on
  // !isGuest, but a session can expire between mount + fetch.
  if (resp.status === 401) {
    return { ok: false, reason: "unavailable", message: "Sign in to get AI recommendations." };
  }

  // 202 = "needs more ratings" — the user has <3 rated vault items.
  // The body has movies: [] + a reason string.
  if (resp.status === 202) {
    const body = (await resp.json().catch(() => ({}))) as AiRecsResponse;
    return {
      ok: false,
      reason: "needs_more_ratings",
      message: body.reason
    };
  }

  // 403 = feature disabled server-side. The rail should hide entirely.
  if (resp.status === 403) {
    return { ok: false, reason: "unavailable", message: "AI recommendations were disabled." };
  }

  // 429 = rate limit. The body has retryAfterSeconds.
  if (resp.status === 429) {
    const body = (await resp.json().catch(() => ({}))) as {
      retryAfterSeconds?: number;
    };
    const secs = body.retryAfterSeconds ?? 60;
    return {
      ok: false,
      reason: "rate_limit",
      message: `Rate limit hit. Try again in ${secs}s.`
    };
  }

  // 503 = Groq failure / parse error / TMDB fetch failure.
  if (resp.status === 503) {
    const body = (await resp.json().catch(() => ({}))) as { hint?: string };
    return {
      ok: false,
      reason: "unavailable",
      message: body.hint || "The recommendation engine is unavailable right now."
    };
  }

  if (!resp.ok) {
    return {
      ok: false,
      reason: "unavailable",
      message: `Request failed (HTTP ${resp.status}).`
    };
  }

  const body = (await resp.json().catch(() => null)) as AiRecsResponse | null;
  if (!body || !Array.isArray(body.movies)) {
    return { ok: false, reason: "unavailable", message: "Malformed response." };
  }

  return { ok: true, data: body };
}

// ─── Component ───────────────────────────────────────────────────

const AiRecommendationRail: Component<AiRecommendationRailProps> = (props) => {
  // The status + recs are fetched via createResource so Solid handles
  // loading + error states declaratively. We use a single resource
  // that chains status → recs to avoid rendering the rail at all when
  // the feature is disabled.
  const [statusData] = createResource(fetchAiStatus);
  const [recsData, { refetch: refetchRecs }] = createResource(
    // Only fetch recs when the status says the feature is enabled.
    () => {
      const status = statusData();
      if (!status || !status.masterEnabled || !status.userRecommendationsEnabled) {
        return null; // sentinel: don't fetch
      }
      if (props.isGuest) return null; // guests have no vault
      return true; // signal to fetch
    },
    async (shouldFetch) => {
      if (!shouldFetch) return null;
      return fetchAiRecs();
    }
  );

  // Derived state for cleaner rendering.
  const status = () => statusData();
  const featureEnabled = () =>
    !!status() && status()!.masterEnabled && status()!.userRecommendationsEnabled;
  const recs = () => recsData();
  const loading = () => statusData.loading || (featureEnabled() && !props.isGuest && recsData.loading);

  // Narrowed memos — these return `null` when the branch doesn't match,
  // so <Show when={successRecs()}> narrows to the `ok: true` branch and
  // <Show when={errorRecs()}> narrows to the `ok: false` branch. This is
  // the idiomatic Solid pattern for discriminated-union narrowing.
  const successRecs = createMemo(() => {
    const r = recs();
    return r && r.ok ? r : null;
  });
  const errorRecs = createMemo(() => {
    const r = recs();
    return r && !r.ok ? r : null;
  });

  // ─── Render ─────────────────────────────────────────────────────
  //
  // Three branches:
  //   1. Status loaded + feature DISABLED → DisabledState (visible,
  //      so the user knows the feature exists but is off).
  //   2. Status loaded + feature ENABLED + not guest → full rail.
  //   3. Otherwise (status loading, or guest) → render nothing.
  //
  // Discriminated union narrowing: we use <Show when={recs()?.ok}> with
  // the callback form `(r) => ...` so TypeScript narrows `r` to the
  // `ok: true` branch. Calling `recs()` repeatedly would defeat narrowing
  // because each call returns a fresh value.

  // Rate-limit seconds memo — extracts retryAfterSeconds from the
  // error result when the reason is "rate_limit".
  const rateLimitSeconds = createMemo(() => {
    const r = errorRecs();
    if (!r || r.reason !== "rate_limit") return 0;
    // Try to parse retryAfterSeconds from the message (e.g. "Rate limit hit. Try again in 60s.")
    const match = r.message?.match(/(\d+)s/);
    return match ? parseInt(match[1], 10) : 60;
  });

  return (
    <Show when={!statusData.loading}>
      {/* Feature disabled — show DisabledState so the user knows the feature exists */}
      <Show when={featureEnabled() === false && !props.isGuest}>
        <section class="discover-fold" aria-label="AI Picks for You">
          <div class="discover-fold-header">
            <div class="discover-fold-label">
              <span
                class="material-symbols-outlined"
                aria-hidden="true"
                style={{ color: "var(--text-muted)" }}
              >
                auto_awesome
              </span>
              AI Picks for You
            </div>
          </div>
          <DisabledState
            featureName="AI Recommendations"
            message="AI recommendations are currently disabled. Check back later."
            icon="auto_awesome"
            variant="section"
          />
        </section>
      </Show>
      {/* Feature enabled + not guest → full rail */}
      <Show when={featureEnabled() && !props.isGuest}>
      <section class="discover-fold" aria-label="AI Picks for You">
        <div class="discover-fold-header">
          <div class="discover-fold-label">
            <span
              class="material-symbols-outlined"
              aria-hidden="true"
              style={{ color: "var(--accent, #00d9a3)" }}
            >
              auto_awesome
            </span>
            AI Picks for You
            {/* Source badge — "Cached" or "Fresh" so the user knows
                whether the recs are from the 24h cache or just generated. */}
            <Show when={successRecs()}>
              {(r) => (
                <span
                  style={{
                    "font-size": "0.625rem",
                    "font-weight": "600",
                    "text-transform": "uppercase",
                    "letter-spacing": "0.05em",
                    color: "var(--text-muted)",
                    "margin-left": "var(--sp-2)",
                    padding: "2px 6px",
                    background: "var(--glass-bg)",
                    border: "1px solid var(--hairline-2)",
                    "border-radius": "var(--radius-sm)"
                  }}
                >
                  {r().data.source === "cache" ? "Cached" : "Fresh"}
                </span>
              )}
            </Show>
          </div>
          {/* Refresh button — forces a re-fetch. The server still
              checks the 24h cache, so this won't burn Groq quota
              unless 24h have passed. */}
          <Show when={!loading() && successRecs()}>
            <button
              type="button"
              class="discover-fold-action focus-ring"
              onClick={() => refetchRecs()}
              aria-label="Refresh AI recommendations"
              title="Refresh AI recommendations"
            >
              <span class="material-symbols-outlined" aria-hidden="true" style={{ "font-size": "1.125rem" }}>
                refresh
              </span>
            </button>
          </Show>
        </div>

        {/* Loading state — skeleton grid (6 cards). */}
        <Show when={loading()}>
          <div class="ai-recs-grid">
            <For each={Array.from({ length: 6 })}>
              {() => (
                <div class="search-rail-card" style={{ cursor: "default" }}>
                  <div class="search-rail-poster skeleton-base" />
                </div>
              )}
            </For>
          </div>
        </Show>

        {/* Success — render the 6 movies in a responsive grid.
            successRecs() narrows the discriminated union to the
            `ok: true` branch, so r().data.movies is type-safe.
            Phase 16 upgrade: replaced the horizontal DiscoverRail with
            a 6-item grid (2 cols mobile, 3 cols tablet, 6 cols desktop)
            so all 6 genre-based recommendations are visible at once
            without scrolling. */}
        <Show when={!loading() && successRecs()}>
          {(r) => (
            <div class="ai-recs-grid">
              <For each={r().data.movies}>
                {(title) => (
                  <button
                    type="button"
                    class="search-rail-card focus-ring"
                    onClick={() => props.onSelect(title)}
                    aria-label={`${title.title || title.name || "Untitled"} — open details`}
                  >
                    <div class="search-rail-poster">
                      <Show
                        when={title.poster_path}
                        fallback={
                          <div class="search-rail-poster-fallback">
                            <span
                              class="material-symbols-outlined"
                              aria-hidden="true"
                            >
                              movie
                            </span>
                          </div>
                        }
                      >
                        <img
                          class="search-rail-poster-img"
                          src={tmdbImage(title.poster_path, "w342")}
                          alt={`${title.title || title.name || "Untitled"} poster`}
                          loading="lazy"
                        />
                      </Show>
                    </div>
                    <p class="search-rail-title">
                      {title.title || title.name || "Untitled"}
                    </p>
                    <Show when={title.release_date || title.first_air_date}>
                      <p class="search-rail-meta">
                        {(title.release_date || title.first_air_date || "").slice(0, 4)}
                        <Show when={title.vote_average}>
                          {" · ★ "}{Number(title.vote_average).toFixed(1)}
                        </Show>
                      </p>
                    </Show>
                  </button>
                )}
              </For>
            </div>
          )}
        </Show>

        {/* Error / needs-more-ratings state.
            errorRecs() narrows to the `ok: false` branch.
            Rate-limit uses RateLimitState with countdown;
            other errors use DiscoverEmptyState. */}
        <Show when={!loading() && errorRecs()}>
          {(r) => (
            <Show
              when={r().reason === "rate_limit"}
              fallback={
                <DiscoverEmptyState
                  icon={
                    r().reason === "needs_more_ratings"
                      ? "rate_review"
                      : "cloud_off"
                  }
                  message={
                    r().message ??
                    (r().reason === "needs_more_ratings"
                      ? "Rate at least 3 movies you love to unlock AI recommendations."
                      : "AI recommendations are unavailable right now.")
                  }
                  hint={
                    r().reason === "unavailable" ? "Click retry to try again." : undefined
                  }
                  onRetry={
                    r().reason !== "needs_more_ratings" ? () => refetchRecs() : undefined
                  }
                />
              }
            >
              <RateLimitState
                retryAfter={rateLimitSeconds()}
                onRetry={() => refetchRecs()}
              />
            </Show>
          )}
        </Show>
      </section>
      </Show>
    </Show>
  );
};

export default AiRecommendationRail;

// Re-export the type for DiscoverPage's prop typing.
export type { AiRecommendationRailProps };
